
// This file was autogenerated by PeakRDL-uvm
package example_uvm;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // Reg - some_register_map::chip_id_reg
    class some_register_map__chip_id_reg extends uvm_reg;
        rand uvm_reg_field rev_num;
        rand uvm_reg_field part_num;

        function new(string name = "some_register_map__chip_id_reg");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.rev_num = new("rev_num");
            this.rev_num.configure(this, 4, 0, "RO", 0, 'h1, 1, 1, 0);
            this.part_num = new("part_num");
            this.part_num.configure(this, 28, 4, "RO", 1, 'h1234567, 1, 1, 0);
        endfunction : build
    endclass : some_register_map__chip_id_reg

    // Reg - some_register_map::enable
    class some_register_map__enable extends uvm_reg;
        rand uvm_reg_field enable;

        function new(string name = "some_register_map__enable");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.enable = new("enable");
            this.enable.configure(this, 1, 0, "WO", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : some_register_map__enable

    // Addrmap - some_register_map
    class some_register_map extends uvm_reg_block;
        rand some_register_map__chip_id_reg chip_id_reg;
        rand some_register_map__enable enable;

        function new(string name = "some_register_map");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.chip_id_reg = new("chip_id_reg");
            this.chip_id_reg.configure(this);

            this.chip_id_reg.build();
            this.default_map.add_reg(this.chip_id_reg, 'h0);
            this.enable = new("enable");
            this.enable.configure(this);

            this.enable.build();
            this.default_map.add_reg(this.enable, 'h4);
        endfunction : build
    endclass : some_register_map

endpackage: example_uvm
