// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package some_register_map_pkg;

    localparam SOME_REGISTER_MAP_DATA_WIDTH = 32;
    localparam SOME_REGISTER_MAP_MIN_ADDR_WIDTH = 3;

    typedef struct {
        logic [27:0] next;
    } some_register_map__chip_id_reg__part_num__in_t;

    typedef struct {
        some_register_map__chip_id_reg__part_num__in_t part_num;
    } some_register_map__chip_id_reg__in_t;

    typedef struct {
        some_register_map__chip_id_reg__in_t chip_id_reg;
    } some_register_map__in_t;

    typedef struct {
        logic value;
    } some_register_map__enable__enable__out_t;

    typedef struct {
        some_register_map__enable__enable__out_t enable;
    } some_register_map__enable__out_t;

    typedef struct {
        some_register_map__enable__out_t enable;
    } some_register_map__out_t;
endpackage