// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module some_register_map (
        input wire clk,
        input wire rst,

        apb3_intf.slave s_apb,

        input some_register_map_pkg::some_register_map__in_t hwif_in,
        output some_register_map_pkg::some_register_map__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [2:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb.PSEL) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb.PWRITE;
                    cpuif_addr <= {s_apb.PADDR[2:2], 2'b0};
                    cpuif_wr_data <= s_apb.PWDATA;
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end
    assign cpuif_wr_biten = '1;

    // Response
    assign s_apb.PREADY = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb.PRDATA = cpuif_rd_data;
    assign s_apb.PSLVERR = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic chip_id_reg;
        logic enable;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.chip_id_reg = cpuif_req_masked & (cpuif_addr == 3'h0);
        decoded_reg_strb.enable = cpuif_req_masked & (cpuif_addr == 3'h4);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } enable;
        } enable;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } enable;
        } enable;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: some_register_map.enable.enable
    always_comb begin
        automatic logic [0:0] next_c = field_storage.enable.enable.value;
        automatic logic load_next_c = '0;
        if(decoded_reg_strb.enable && decoded_req_is_wr) begin // SW write 1 toggle
            next_c = field_storage.enable.enable.value ^ (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.enable.enable.next = next_c;
        field_combo.enable.enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.enable.enable.load_next) begin
            field_storage.enable.enable.value <= field_combo.enable.enable.next;
        end
    end
    assign hwif_out.enable.enable.value = field_storage.enable.enable.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    
    // Assign readback values to a flattened array
    logic [31:0] readback_array[1];
    assign readback_array[0][3:0] = (decoded_reg_strb.chip_id_reg && !decoded_req_is_wr) ? 'h1 : '0;
    assign readback_array[0][31:4] = (decoded_reg_strb.chip_id_reg && !decoded_req_is_wr) ? hwif_in.chip_id_reg.part_num.next : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<1; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule